import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildBn128, unstringifyBigInts } from "ffjavascript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const vk = unstringifyBigInts(
  JSON.parse(readFileSync(join(root, "build/verification_key.json"), "utf8")),
);

const curve = await buildBn128();

function g1(p) {
  const b = curve.G1.toUncompressed(curve.G1.fromObject(p));
  return Array.from(b);
}

function g2(p) {
  const b = curve.G2.toUncompressed(curve.G2.fromObject(p));
  return Array.from(b);
}

function arr(bytes) {
  return bytes.map((x) => x.toString().padStart(3, " ")).join(", ");
}

function g1const(name, bytes) {
  return `pub const ${name}: [u8; 64] = [\n    ${chunk(bytes, 16)}\n];`;
}

function g2const(name, bytes) {
  return `pub const ${name}: [u8; 128] = [\n    ${chunk(bytes, 16)}\n];`;
}

function chunk(bytes, n) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += n) {
    lines.push(bytes.slice(i, i + n).map((x) => x.toString().padStart(3, " ")).join(", "));
  }
  return lines.join(",\n    ");
}

const alpha = g1(vk.vk_alpha_1);
const beta = g2(vk.vk_beta_2);
const gamma = g2(vk.vk_gamma_2);
const delta = g2(vk.vk_delta_2);
const ic = vk.IC.map(g1);

const rust = `// Generated by circuits/scripts/export-vk.mjs — do not edit by hand.
pub const NR_PUBINPUTS: usize = ${vk.nPublic};

${g1const("VK_ALPHA_G1", alpha)}

${g2const("VK_BETA_G2", beta)}

${g2const("VK_GAMMA_G2", gamma)}

${g2const("VK_DELTA_G2", delta)}

pub const VK_IC: [[u8; 64]; ${ic.length}] = [
${ic.map((b) => `    [\n        ${chunk(b, 16)}\n    ]`).join(",\n")}
];
`;

const out = join(root, "../programs/zkctf/src/verifying_key.rs");
writeFileSync(out, rust);
writeFileSync(join(root, "build/vk.meta.json"), JSON.stringify({ nPublic: vk.nPublic, ic: ic.length }, null, 2));
console.log("wrote", out, "nPublic=", vk.nPublic);
await curve.terminate();
