export type Lang = "en" | "tr" | "es";

export const copy = {
  en: {
    play: "CTF",
    learn: "Academy",
    docs: "Docs",
    join: "Join",
    account: "Account",
    pitch: "Learn security from real hacks. Prove it with Groth16. Get paid from the pot.",
    pitchLead: "Cybersecurity training is expensive and rarely built on real incidents. ZKCTF publishes AI-assisted, human-reviewed lessons every week, in cybersecurity and the math behind it, each one a reproduced real-life hack. Membership costs a few USDC a month. The Saturday on-chain CTF pays the top 10 from a 5 USDC pot, and a Groth16 proof shows you solved it without the flag ever touching the chain.",
    joinTitle: "This week’s race",
    joinLead: "Saturday race on Solana Devnet: 5 USDC pot, curated CTFs, Groth16 submit, top 10 share 80%. The flag stays off-chain. Entry is live on Devnet.",
    liveBadge: "Live on Devnet",
    raceLive: "Enter the race on Devnet →",
    devnetLive: "Live on Solana Devnet. Pay with devnet USDC (free from faucet.circle.com).",
    connectFirst: "Connect a wallet first.",
    locked: "Enter this week with 5 USDC to open the puzzles.",
    enterBtn: "Enter · 5 USDC",
    entered: "You’re in this week.",
    flagOkPending: "That’s the right flag. We’re still finishing a one-time setup, so it isn’t on the board yet.",
    hint: "Need a hint?",
    submit: "Submit",
    saved: "Saved. You’re on the board.",
    rejected: "That flag doesn’t match. Try again.",
    themeLight: "Light mode",
    themeDark: "Dark mode",
    ctfNext: "Next CTF in",
    ctfLive: "CTF is live",
    ctfEnds: "Ends in",
    ctfWhen: "Saturdays, 18:00 Istanbul / 12:00 Buenos Aires. 24 hours. 5 USDC. Top 10 share 80% of the pot.",
    accountLead: "Your wallet is your login. Membership and race entry are paid in USDC on-chain. No cards, no stored payment details.",
    officialSet: "This week’s CTFs",
    network: "Devnet · live",
    seasonPoints: "Season points",
    seasonBadge: "Badge",
    prestigeNote: "Season points stay on this wallet. They are not transferable.",
    noLevels: "No CTFs yet this week.",
    ctfLinearLead: "Linear race: finish CTF #1 before #2 opens. You must clear every CTF this week to be eligible for the pot.",
    ctfLocked: "Clear the previous CTF first.",
    ctfLockedTitle: "Locked",
    ctfDone: "Solved. Next CTF is unlocked.",
    ctfCleared: "All CTFs cleared — you’re on the winner board for this week.",
    academyTitle: "ZKCTF Academy",
    academyLead: "New lessons every week in two tracks: cybersecurity and math for cybersecurity. Each security lesson rebuilds a real incident; each math lesson teaches the math that broke or protected a real system. AI drafts, a human editor checks and publishes. Every lesson ends with a practice flag.",
    trackAll: "All",
    lessonLocked: "Members only. Join below to read the full lesson.",
    lessonRead: "Read lesson",
    lessonHide: "Hide",
    lessonSolved: "Solved",
    lessonCase: "Real case",
    lessonSources: "Sources",
    lessonEarly: "Founding early access",
    lessonEmpty: "No lessons published yet.",
    lessonLoadError: "Lessons could not be loaded. The server may be restarting.",
    retry: "Retry",
    lessonReviewed: "Reviewed by",
    lessonCorrect: "Correct. Lesson marked as solved.",
    membershipTitle: "Academy membership",
    membershipLead: "One plan, paid in USDC on-chain. No cards, no auto-renew: pay for 1, 3 or 12 months and extend whenever you like. The Saturday race is a separate 5 USDC entry.",
    month1: "1 month",
    month3: "3 months",
    month12: "12 months",
    payUsdc: "Pay with USDC",
    paying: "Waiting for wallet…",
    paid: "Paid. Your membership is on-chain.",
    memberUntil: "Member until",
    foundingTitle: "Founding member perk",
    foundingLead: "The first 100 wallets become Founding members: 50% off for as long as you renew, a Founding badge, and every new lesson 24 hours before everyone else.",
    foundingLeft: "Founding seats left",
    foundingYou: "You’re a Founding member. Your price is locked.",
    foundingGone: "All Founding seats are taken.",
    membership: "Membership",
    tierFounding: "Founding",
    tierMember: "Member",
    legal: "Legal",
    footerRights: "Open source under Apache-2.0.",
    footerLegalBlurb:
      "Race USDC sits in the on-chain pot until settle. Membership is paid in USDC on-chain. See Legal for privacy and program notes.",
    legalTitle: "Legal",
    legalLead: "Short notes. Not a substitute for counsel in your jurisdiction.",
    privacyTitle: "Privacy",
    privacyBody:
      "We use your wallet address for entry, scoring, membership and lesson progress. We do not sell personal data. All payments are USDC transfers on Solana; we never handle card data. Theme and language may be stored in your browser (cookie / localStorage).",
    escrowTitle: "Escrow program",
    escrowBody:
      "Saturday race fees are 5 USDC into a program pot ATA. Board credit and payout require on-chain Groth16 submit + settle (fixed split_pot: 20% treasury, 80% top 10). Academy membership USDC goes to the treasury and never touches the race pot or board. Host demo may unlock Play without a chain enter — production races require on-chain enter + verify.",
    contactTitle: "Contact",
    contactBody: "Project links and source: GitHub (icon in the footer).",
  },
  tr: {
    play: "CTF",
    learn: "Akademi",
    docs: "Docs",
    join: "Katıl",
    account: "Hesap",
    pitch: "Güvenliği gerçek hack’lerden öğren. Groth16 ile kanıtla. Pottan kazan.",
    pitchLead: "Siber güvenlik eğitimi pahalı ve nadiren gerçek olaylara dayanıyor. ZKCTF her hafta yapay zekâ destekli, insan editörden geçmiş dersler yayınlar: siber güvenlik ve arkasındaki matematik, her biri yeniden kurgulanmış gerçek bir hack. Üyelik ayda birkaç USDC. Cumartesi zincir üstü CTF’te 5 USDC’lik pot ilk 10’a dağıtılır; Groth16 kanıtı çözdüğünü gösterir, flag zincire hiç yazılmaz.",
    joinTitle: "Bu haftanın yarışı",
    joinLead: "Solana Devnet Cumartesi: 5 USDC pot, curated CTF, Groth16 submit, ilk 10 %80. Flag zincirde yok. Devnet’te giriş açık.",
    liveBadge: "Devnet’te canlı",
    raceLive: "Devnet’te yarışa gir →",
    devnetLive: "Solana Devnet’te canlı. Devnet USDC ile öde (faucet.circle.com’dan ücretsiz).",
    connectFirst: "Önce cüzdanını bağla.",
    locked: "Soruları açmak için bu haftaya 5 USDC ile gir.",
    enterBtn: "Gir · 5 USDC",
    entered: "Bu hafta içindesin.",
    flagOkPending: "Flag doğru. Tek seferlik kurulum bitmediği için henüz sıralamaya yazılamadı.",
    hint: "İpucu ister misin?",
    submit: "Gönder",
    saved: "Kaydedildi. Sıralamadasın.",
    rejected: "Bu flag uymadı. Tekrar dene.",
    themeLight: "Açık tema",
    themeDark: "Koyu tema",
    ctfNext: "Sıradaki CTF",
    ctfLive: "CTF açık",
    ctfEnds: "Bitişe",
    ctfWhen: "Cumartesi 18:00 İstanbul / 12:00 Buenos Aires. 24 saat. 5 USDC. İlk 10 potun %80’ini paylaşır.",
    accountLead: "Giriş cüzdanın. Üyelik ve yarış girişi zincir üstünde USDC ile ödenir. Kart yok, saklanan ödeme bilgisi yok.",
    officialSet: "Bu haftanın CTF’leri",
    network: "Devnet · canlı",
    seasonPoints: "Sezon puanı",
    seasonBadge: "Rozet",
    prestigeNote: "Sezon puanı bu cüzdanda kalır. Transfer edilemez.",
    noLevels: "Bu hafta henüz CTF yok.",
    ctfLinearLead: "Sıralı yarış: CTF #1 bitmeden #2 açılmaz. Pota hak kazanmak için bu haftanın bütün CTF’lerini bitirmelisin.",
    ctfLocked: "Önce bir önceki CTF’i bitir.",
    ctfLockedTitle: "Kilitli",
    ctfDone: "Çözüldü. Sıradaki CTF açıldı.",
    ctfCleared: "Tüm CTF’ler bitti — bu hafta kazanan sırasındasın.",
    academyTitle: "ZKCTF Akademi",
    academyLead: "Her hafta iki alanda yeni dersler: siber güvenlik ve siber güvenlik için matematik. Her güvenlik dersi gerçek bir olayı yeniden kurar; her matematik dersi gerçek bir sistemi kıran ya da koruyan matematiği öğretir. Taslağı yapay zekâ yazar, insan editör kontrol edip yayınlar. Her ders bir pratik flag ile biter.",
    trackAll: "Hepsi",
    lessonLocked: "Yalnız üyeler. Dersin tamamı için aşağıdan katıl.",
    lessonRead: "Dersi oku",
    lessonHide: "Gizle",
    lessonSolved: "Çözüldü",
    lessonCase: "Gerçek olay",
    lessonSources: "Kaynaklar",
    lessonEarly: "Founding erken erişim",
    lessonEmpty: "Henüz yayınlanmış ders yok.",
    lessonLoadError: "Dersler yüklenemedi. Sunucu yeniden başlıyor olabilir.",
    retry: "Tekrar dene",
    lessonReviewed: "İnceleyen",
    lessonCorrect: "Doğru. Ders çözüldü olarak işaretlendi.",
    membershipTitle: "Akademi üyeliği",
    membershipLead: "Tek plan, zincir üstünde USDC ile. Kart yok, otomatik yenileme yok: 1, 3 ya da 12 ay öde, istediğin zaman uzat. Cumartesi yarışı ayrı bir 5 USDC giriş.",
    month1: "1 ay",
    month3: "3 ay",
    month12: "12 ay",
    payUsdc: "USDC ile öde",
    paying: "Cüzdan bekleniyor…",
    paid: "Ödendi. Üyeliğin zincirde.",
    memberUntil: "Üyelik bitişi",
    foundingTitle: "Founding üye ayrıcalığı",
    foundingLead: "İlk 100 cüzdan Founding üye olur: yeniledikçe %50 indirim, Founding rozeti ve her yeni derse herkesten 24 saat önce erişim.",
    foundingLeft: "Kalan Founding koltuk",
    foundingYou: "Founding üyesin. Fiyatın sabit.",
    foundingGone: "Founding koltukların hepsi doldu.",
    membership: "Üyelik",
    tierFounding: "Founding",
    tierMember: "Üye",
    legal: "Legal",
    footerRights: "Apache-2.0 lisanslı açık kaynak.",
    footerLegalBlurb:
      "Yarış USDC’si settle’a kadar zincir potunda. Üyelik zincir üstünde USDC ile ödenir. Gizlilik için Legal.",
    legalTitle: "Legal",
    legalLead: "Kısa notlar. Bulunduğun ülkedeki hukuki danışmanın yerine geçmez.",
    privacyTitle: "Gizlilik",
    privacyBody:
      "Cüzdan adresini giriş, skor, üyelik ve ders ilerlemesi için kullanırız. Kişisel veri satmayız. Bütün ödemeler Solana üzerinde USDC transferidir; kart verisiyle hiç uğraşmayız. Tema/dil tarayıcıda saklanabilir.",
    escrowTitle: "Escrow program",
    escrowBody:
      "Cumartesi giriş 5 USDC program pot ATA’ya gider. Sıra ve ödeme yalnız on-chain Groth16 submit + settle (sabit split_pot: %20 treasury, %80 ilk 10). Akademi üyeliği USDC’si treasury’ye gider; yarış potuna ve sıralamaya dokunmaz. Host demo zincir enter olmadan Play açabilir — üretimde on-chain enter + verify şart.",
    contactTitle: "İletişim",
    contactBody: "Proje linkleri ve kaynak: footer’daki GitHub ikonu.",
  },
  es: {
    play: "CTF",
    learn: "Academia",
    docs: "Docs",
    join: "Entrar",
    account: "Cuenta",
    pitch: "Aprendé seguridad con hacks reales. Probalo con Groth16. Cobrá del pozo.",
    pitchLead: "La formación en ciberseguridad es cara y rara vez se basa en incidentes reales. ZKCTF publica cada semana clases asistidas por IA y revisadas por una persona, de ciberseguridad y de la matemática detrás, cada una un hack real reconstruido. La membresía cuesta unos pocos USDC al mes. El CTF on-chain del sábado paga al top 10 desde un pozo de 5 USDC, y una prueba Groth16 muestra que resolviste sin que el flag toque la chain.",
    joinTitle: "Carrera de esta semana",
    joinLead: "Carrera del sábado en Solana Devnet: pozo 5 USDC, CTFs curados, submit Groth16, top 10 con el 80%. El flag no está en la chain. La entrada ya está activa en Devnet.",
    liveBadge: "En vivo en Devnet",
    raceLive: "Entrá a la carrera en Devnet →",
    devnetLive: "En vivo en Solana Devnet. Pagá con USDC de devnet (gratis en faucet.circle.com).",
    connectFirst: "Conectá la wallet primero.",
    locked: "Entrá esta semana con 5 USDC para abrir las preguntas.",
    enterBtn: "Entrar · 5 USDC",
    entered: "Ya estás adentro esta semana.",
    flagOkPending: "El flag es correcto. Todavía estamos terminando un setup, así que aún no está en el ranking.",
    hint: "¿Un hint?",
    submit: "Enviar",
    saved: "Guardado. Ya estás en el ranking.",
    rejected: "Ese flag no coincide. Probá de nuevo.",
    themeLight: "Modo claro",
    themeDark: "Modo oscuro",
    ctfNext: "Próximo CTF",
    ctfLive: "CTF en vivo",
    ctfEnds: "Termina en",
    ctfWhen: "Sábados, 18:00 Estambul / 12:00 Buenos Aires. 24 horas. 5 USDC. El top 10 se lleva el 80% del pozo.",
    accountLead: "Tu wallet es el login. La membresía y la entrada a la carrera se pagan en USDC on-chain. Sin tarjetas, sin datos de pago guardados.",
    officialSet: "CTFs de esta semana",
    network: "Devnet · live",
    seasonPoints: "Puntos de temporada",
    seasonBadge: "Insignia",
    prestigeNote: "Los puntos de temporada quedan en esta wallet. No se transfieren.",
    noLevels: "Todavía no hay CTFs esta semana.",
    ctfLinearLead: "Carrera lineal: terminá CTF #1 antes de que abra #2. Tenés que completar todos los CTFs de la semana para entrar al pozo.",
    ctfLocked: "Primero completá el CTF anterior.",
    ctfLockedTitle: "Bloqueado",
    ctfDone: "Resuelto. El siguiente CTF está abierto.",
    ctfCleared: "Todos los CTFs listos — estás en el ranking de ganadores de esta semana.",
    academyTitle: "Academia ZKCTF",
    academyLead: "Clases nuevas cada semana en dos líneas: ciberseguridad y matemática para ciberseguridad. Cada clase de seguridad reconstruye un incidente real; cada clase de matemática enseña la matemática que rompió o protegió un sistema real. La IA hace el borrador, una persona lo revisa y lo publica. Cada clase termina con un flag de práctica.",
    trackAll: "Todas",
    lessonLocked: "Solo miembros. Sumate abajo para leer la clase completa.",
    lessonRead: "Leer clase",
    lessonHide: "Ocultar",
    lessonSolved: "Resuelta",
    lessonCase: "Caso real",
    lessonSources: "Fuentes",
    lessonEarly: "Acceso anticipado Founding",
    lessonEmpty: "Todavía no hay clases publicadas.",
    lessonLoadError: "No se pudieron cargar las clases. El servidor puede estar reiniciando.",
    retry: "Reintentar",
    lessonReviewed: "Revisada por",
    lessonCorrect: "Correcto. Clase marcada como resuelta.",
    membershipTitle: "Membresía de la Academia",
    membershipLead: "Un solo plan, pagado en USDC on-chain. Sin tarjetas ni renovación automática: pagá 1, 3 o 12 meses y extendé cuando quieras. La carrera del sábado es una entrada aparte de 5 USDC.",
    month1: "1 mes",
    month3: "3 meses",
    month12: "12 meses",
    payUsdc: "Pagar con USDC",
    paying: "Esperando la wallet…",
    paid: "Pagado. Tu membresía está on-chain.",
    memberUntil: "Miembro hasta",
    foundingTitle: "Beneficio Founding",
    foundingLead: "Las primeras 100 wallets son miembros Founding: 50% de descuento mientras renueves, insignia Founding y cada clase nueva 24 horas antes que el resto.",
    foundingLeft: "Lugares Founding libres",
    foundingYou: "Sos miembro Founding. Tu precio queda fijo.",
    foundingGone: "Se ocuparon todos los lugares Founding.",
    membership: "Membresía",
    tierFounding: "Founding",
    tierMember: "Miembro",
    legal: "Legal",
    legalTitle: "Legal",
    legalLead: "Notas cortas. No sustituyen asesoramiento legal en tu jurisdicción.",
    privacyTitle: "Privacidad",
    footerRights: "Código abierto bajo Apache-2.0.",
    footerLegalBlurb:
      "El USDC de la carrera queda en el pozo on-chain hasta settle. La membresía se paga en USDC on-chain. Ver Legal.",
    privacyBody:
      "Usamos tu wallet para entrada, scoring, membresía y progreso de clases. No vendemos datos. Todos los pagos son transferencias USDC en Solana; nunca manejamos datos de tarjeta. Tema/idioma pueden guardarse en el navegador.",
    escrowTitle: "Programa escrow",
    escrowBody:
      "La entrada del sábado (5 USDC) va a un pozo ATA del programa. Ranking y pago exigen submit Groth16 on-chain + settle (split_pot fijo: 20% tesoro, 80% top 10). El USDC de la membresía va al tesoro y nunca toca el pozo ni el ranking. El demo del host puede abrir Play sin enter — en producción hace falta enter + verify.",
    contactTitle: "Contacto",
    contactBody: "Enlaces del proyecto y código: el ícono de GitHub en el footer.",
  },
} as const;
